#!/usr/bin/env bash
#Script that configures a brand new Ubuntu Machine to the requirements asked in the task

sudo apt update
sudo apt-get -y install nginx
sudo sed -i "/listen 80 default_server/a add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-enabled/default
sudo service nginx restart
